// Copyright 2023 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics --input /home/elpekenin/dev_qmk/keyboards/handwired/onekey/keymaps/ls0xx/painter/images/bw.gif --output /home/elpekenin/dev_qmk/keyboards/handwired/onekey/keymaps/ls0xx/painter/images --format mono2 --no-rle False --no-deltas False`

#pragma once

#include <qp.h>

extern const uint32_t gfx_bw_length;
extern const uint8_t  gfx_bw[10186];
